### ISSUE TITLE
Windows branch requires api-ms-win-core-winrt-string-l1-1-0.dll

### ISSUE THREAD

**Issue by gilescope** [dalance/procs#11]
But alas MS says that's not available on Windows 7:

https://docs.microsoft.com/en-gb/windows/desktop/apiindex/windows-apisets

This is more a historical record in case anyone else gets the same error message. I'm guessing the recommended fix for this is to upgrade one's OS...

**Comment by gilescope** [comment]
It compiles and links ok on windows 7 though :-)

**Comment by dalance** [comment]
Currently windows branch is for investigation only.
It uses new WinRT api, so it may require Windows10.
I'll plan to implement by old win32api for compatibility and performance.

**Comment by dalance** [comment]
I updated windows branch.
I think it is available on Windows 7. Could you try it?
