### ISSUE TITLE
Use minus for the pager

### ISSUE THREAD

**Issue by arijit79** [dalance/procs#119]
I saw the README of `procs` and found that pager support on Windows is experimental and I can guess the reason is no good pager is available there that. The other option is to distribute it alongside `procs` which would require Mingw to be distributed. 

This is where `minus` comes to the rescue, it's cross-platform Rust library for sync as well async paging. I think that would very easily solve this problem

**Disclosure**: I am the author of `minus`

**Comment by dalance** [comment]
Thanks!

I was interesting in `minus`, and tried it previously.
However, at that time, the pager scroll was not smooth.
(According to my memory, each line scroll caused full screen refresh)

It may be the wrong usage. I'll try it again.

**Comment by arijit79** [comment]
Well it's still the case. Each line scroll causes a full screen refresh but it's in the design of `minus` There's no way you can pop out lines of terminal or push at the end of it. Maybe if someone goes through a full rewrite he/she can think of better algorithms

**Comment by dalance** [comment]
OK.
I think smooth scroll is better because full screen refresh in a large terminal with Full-HD/4K display is slow.
Anyway, `minus` can be used as Windows pager at least. I'll try later.

**Comment by dalance** [comment]
I added `minus` as built-in pager, and now pager is supported on Windows.
Already `minus` seems to have smooth scroll, it's very good.
