### ISSUE TITLE
Add option to show process age (etimes)

### ISSUE THREAD

**Issue by HeinrichHartmann** [dalance/procs#120]
User Story:
As a user, I want to be able see the process age (elapsed time in seconds since process started) in a column.

Use case: 
Check if a process was recently restarted, e.g. `procs emacs`

Alternatives considered:
- CpuTime -- only shows time spent on CPU. As an idle process does not consume CPU, this is not helpful for this use case
- StartTime -- requires me know the current time and take a delta

PS: Great tool. Thanks for making this!

**Comment by dalance** [comment]
Thank you for your proposal.
I added `ElapsedTime` column like below.

![image](https://user-images.githubusercontent.com/4331004/118638482-db695400-b811-11eb-9e8f-d8c79b48662f.png)

I'll release the next version after GitHub Actions becomes stable.

**Comment by dalance** [comment]
I released v0.11.7.
