### ISSUE TITLE
snap version of procs is outdate sitting at v0.10.10. Please update it.

### ISSUE THREAD

**Issue by PranavBhattarai** [dalance/procs#121]
I think it would be nice if we roll an update there _unless there is some problem doing it._
![image](https://user-images.githubusercontent.com/32763112/108699425-51b92b80-752d-11eb-83b7-301c9e827c24.png)

**Comment by dalance** [comment]
Thanks!
I updated the stable release.

**Comment by PranavBhattarai** [comment]
@dalance Thanks a lot.
![image](https://user-images.githubusercontent.com/32763112/108705184-14f13280-7535-11eb-8c21-d6cae027de12.png)
