### ISSUE TITLE
Crashes when piped to fzf

### ISSUE THREAD

**Issue by yuki-yano** [dalance/procs#146]
When I pipe the result of the procs command to fzf, fzf crashes with high probability.
In rare cases it works fine, but success is random.

The smallest command to reproduce
`$ procs | fzf`

**Comment by dalance** [comment]
Thank you for your report.
I fixed it.

I'll release the next version after GitHub Actions becomes stable.

**Comment by dalance** [comment]
I released v0.11.7.
