### ISSUE TITLE
Panic on Open

### ISSUE THREAD

**Issue by jeff-hykin** [dalance/procs#147]
The command doesnt respond till I press enter, then it shows processes but is missing the header line.
I'm not sure if this is related to previous issues

Here's the output after trying to run procs
```shell
➜ export RUST_BACKTRACE=full && procs

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/jeffhykin/.cargo/registry/src/github.com-1ecc6299db9ec823/termbg-0.2.3/src/lib.rs:229:25
stack backtrace:

~ via ⬢ v15.14.0 took 37s 
```

Here is the line and file that is being referenced in that error
![Screen Shot 2021-05-18 at 4 20 36 PM](https://user-images.githubusercontent.com/17692058/118725102-1741f080-b7f5-11eb-9cfb-e1c977708cfe.png)

- Running procs with sudo creates the same result
- I installed procs through cargo.
- System info:
```
➜ uname -a
Darwin Jeffs-MacBookPro-2.local 17.7.0
Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018;
root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

**Comment by dalance** [comment]
Thank you for your report.
Does the previous version work fine?

```
$ cargo install --version 0.11.5 procs
```

**Comment by dcarbone** [comment]
I experienced this same issue with latest from snap stable, which appears to be v0.11.3.  Upgrading to edge, which at the moment is v0.11.8 resolved this issue for me.

**Comment by dalance** [comment]
Thanks!
I updated the stable to v0.11.8.

**Comment by jeff-hykin** [comment]
> Thank you for your report.
> Does the previous version work fine?
> 
> ```
> $ cargo install --version 0.11.5 procs
> ```

Sorry I totally missed this response. Thank you!
