### ISSUE TITLE
Case insensitive search?

### ISSUE THREAD

**Issue by rushi** [dalance/procs#159]
Is it possible todo a case-insensitive search? So `procs foo` returns the same results as `procs FOO`

**Comment by ztlevi** [comment]
It would be great use smart case as default

**Comment by HarrisonMc555** [comment]
This would be super, super helpful!

**Comment by dalance** [comment]
I added `case` option to config.toml, and changed the default to smart case.

https://github.com/dalance/procs#case

**Comment by sergiorgiraldo** [comment]
on v 0.12.3 i tried this on my ~/procs.toml:
```
[[columns]]
kind = "Command"
case = "Insensitive"

[search]
case = "Insensitive"
```

It does not perform case insensitive (it does work if i fire the `-I` command)
