### ISSUE TITLE
Can't add new columns with default config

### ISSUE THREAD

**Issue by lilyball** [dalance/procs#180]
With the default config, there doesn't appear to be a way to add any new columns from the command-line. In particular, the only way to add columns from the command-line is with the `--insert` flag, which requires a defined Slot to use.

Two issues:
1. The default config has no Slots. It really should have at least one.
2. The `--insert` flag does not print any warning if there is no Slot. This means that, with default config, running e.g. `procs -i Pgid` just displays the normal `procs` output without informing me as to why it didn't work.

I'm also concerned that even if the default config adds a Slot column, I'll run into a case where I want to add more columns than there are Slots in the default config. This could be handled by allowing a single Slot to be replaced by multiple inserted columns (or by having a "Slots" that is used for any inserted column where there is no "Slot" available).

**Comment by dalance** [comment]
Thank you for your suggestion.
I added `MultiSlot` column, and added it to the default config.
Now many `--insert` can be used by default.

![image](https://user-images.githubusercontent.com/4331004/137890560-135d4ea3-9dd3-45ae-ab48-f17f854eec16.png)
