### ISSUE TITLE
Noob question -- large.toml

### ISSUE THREAD

**Issue by STashakkori** [dalance/procs#189]
Hello. Here is a noobie question. How can I set to use the large.toml?

It appears that the default is the small? Basically I want to see the process states and am not seeing them

**Comment by dalance** [comment]
If you use linux, the large.toml can be used like below:

```
$ cp large.toml ~/.procs.toml
```

More detail is https://github.com/dalance/procs#configuration.

**Comment by STashakkori** [comment]
Thank you so much
