### ISSUE TITLE
Packaging: Alpine Linux

### ISSUE THREAD

**Issue by 5paceToast** [dalance/procs#19]
Hi, procs is now available in the official Alpine Linux [repos](https://pkgs.alpinelinux.org/packages?name=procs).
I'm not sure how you want installation instructions formatted, so here is a summary:

1. Ensure that the correct repository (see above link for the most up-to-date information) is enabled.
2. `apk add procs`

Enjoy! :)

**Comment by dalance** [comment]
Thanks! I added the instruction for Alpine Linux.
