### ISSUE TITLE
Treat tree column as ordinary column

### ISSUE THREAD

**Issue by thorstenkampe** [dalance/procs#196]
I'd like to display the tree column left to the command column to get a more `htop` like view. Is it possible to make the tree column configurable like any other column in `config.toml`?

**Comment by dalance** [comment]
I added `TreeSlot` to configure tree column position.

![image](https://user-images.githubusercontent.com/4331004/177263422-1a528899-6901-4de2-8009-12bddfb28908.png)

If there is `TreeSlot` in config, tree column is shown at the slot position.

```toml
...
[[columns]]
kind = "TreeSlot"
...
```
