### ISSUE TITLE
inconsistent segfaults in the test suite

### ISSUE THREAD

**Issue by 5paceToast** [dalance/procs#20]
When running tests in the packaging process, sometimes, a test will fail with a segfault (invalid memory reference).
I analyzed what was happening, but couldn't come to a definitive conclusion.

Would it be possible to investigate this?
For now tests are disabled for packaging purposes (since it wouldn't be nice to require continual re-runs until it passes), but it would be nice to be able to re-enable them.

To reproduce (note: this is inconsistent, both on where it fails and whether if fails):
1. Launch an alpine vm/container/system/whatever (ideally edge)
2. Install alpine-sdk
3. Clone the alpine ports tree (depth=1 is fine for this purpose; it can be found in multiple places, and may actually move soon (a transition to gitlab is currently ongoing); at the time of writing, `git://git.alpinelinux.org/aports` is appropriate)
4. Ensure your user is part of the `abuild` group and it's registered (for root, you'll need to install `shadow` and use `newgrp`)
5. Enter `aports/*/procs`
6. Run `abuild fetch unpack prepare build` (if root, you will need the `-F` flag)
7. Run `abuild check` (see flag above) - this is the isolated "run tests" step, and will trigger even though tests are (currently) disabled.

**Comment by dalance** [comment]
Thank you for your report.
I'll investigate it.

**Comment by dalance** [comment]
I fixed it and released v0.8.8.

**Comment by 5paceToast** [comment]
Works for me, thanks!. That's very impressive RTT!
