### ISSUE TITLE
Please provide a default config to start from

### ISSUE THREAD

**Issue by igor-petruk** [dalance/procs#22]
Currently if you have no config, you have all columns. For example if one of your apps opens many ports, you have gigantic list of ports, forcing all command out of our screen.

Commands should be closer. So I try to write a config, but a moment I create a config I am empty handed. The app won't even start with empty columsn list.

One way it is to start from the config from README, but it has too few columns to start with, now I have to list them all.

I wonder if we could start wil full config as default and do cosmetic changes on it.

**Comment by dalance** [comment]
`procs --config` shows the current config. So if there is no config, it shows the default config.
Please do `procs --config > ~/.procs.toml` and edit `~/.procs.toml`.

**Comment by dalance** [comment]
Additionally I will consider about max column width setting to prevent gigantic list of ports. Thanks.

**Comment by igor-petruk** [comment]
Oh, that is exactly what I wanted. I don't know how I didn't find it. Thanks, feel free to close!
