### ISSUE TITLE
`procs --sortd rss` doesn't show memory column

### ISSUE THREAD

**Issue by abitrolly** [dalance/procs#227]
```
$ procs --sortd rss
 PID:▲ User            │ TTY    CPU  MEM CPU Time │ Command                                                                                                              >
                       │        [%]  [%]          │                                                                                                                      >
 1     root            │        0.0  0.1 00:00:05 │ /usr/lib/systemd/systemd rhgb --switched-root --system --deserialize 31            
```

**Comment by dalance** [comment]
rss is not shown by default.
`--sortd` only sorts the specified column, do nothing if the column is not found.
If you want it, `VmRss` column can be added to your configuration file.
Please see the following file.
https://github.com/dalance/procs/blob/master/config/large.toml

**Comment by abitrolly** [comment]
I was looking for a lightweight replacement for `ps` and having to configure `procs` in addition to installation on every server I may need to inspect memory usage is too cumbersome. Unfortunately.

**Comment by dalance** [comment]
If you want to do without config,  you can `procs --insert rss --sortd rss`.

**Comment by abitrolly** [comment]
Why not to turn on the column automatically if specified?

**Comment by dalance** [comment]
There is no reason. I'll consider it, but I don't have the enough time to implement now.

**Comment by abitrolly** [comment]
Understand. Will a PR be accepted to provide that behavior?

**Comment by dalance** [comment]
> Understand. Will a PR be accepted to provide that behavior?

Yes

**Comment by sou-chon** [comment]
@dalance I have opened a PR. Any chance to get it reviewed?
