### ISSUE TITLE
Extract libproc to separate library (macos)

### ISSUE THREAD

**Issue by mlesin** [dalance/procs#23]
Do you have any plans to extract your version of libproc implementation to separate library? I know there exists one already, but your version seems to have much more features implemented.
I'm looking for ability to get information about cpu/memory usage of some process tree in my project

**Comment by dalance** [comment]
libproc-rs has a plan to refactor.
https://github.com/andrewdavidmackenzie/libproc-rs/issues/20

So l plan to create PR after the refactoring.

**Comment by dalance** [comment]
libproc-rs v0.5.0 with `pid_rusage` was released.
