### ISSUE TITLE
Sourcing shell completion doesn't work

### ISSUE THREAD

**Issue by Pound-Hash** [dalance/procs#269]
Per [readme](https://github.com/dalance/procs#shell-completion), when I run: `source <(procs --completion-out zsh)` I receive the error: `_arguments:comparguments:325: can only be called from completion function`

zsh 5.8.1

**Comment by dalance** [comment]
zsh may not support `source` directly.
Could you try like `procs --completion-out zsh > ~/.zsh/function/_procs`?

**Comment by Pound-Hash** [comment]
I found `_procs` in an fpath dir already. The Arch package put it there.
