### ISSUE TITLE
Procs hangs, even in a "normal" terminal

### ISSUE THREAD

**Issue by dtomvan** [dalance/procs#288]
I am using `st` (https://github.com/dtomvan/st).

`procs --version`: `procs 0.12.2`.
`procs --pager disable --theme dark` works.
`procs` hangs.
`procs --debug` also prints nothing and hangs.

I am on (vanilla) Arch Linux. The package is `community/procs 0.12.2-1`.
Testing it on Alacritty, gnome-terminal, Kitty and urxvt does work as intended.

My st config consists of (not too many) patches and a color scheme, so I have no idea how this happens.
Testing on stock st `baa9357e9` also doesn't work, so it's probably not specific to my version.

See also: #142

**Comment by dalance** [comment]
`st` seems to ignore xterm DSR request to be used for theme detection sequence.
I added a sequence to check the case, now st may be used.

**Comment by dalance** [comment]
I released v0.14.0.
