### ISSUE TITLE
Column sizing

### ISSUE THREAD

**Issue by dcarosone** [dalance/procs#3]
The column widths seem to be calculated from the full dataset, rather than the subset that will actually get displayed.

![image](https://user-images.githubusercontent.com/11495017/52112283-27505900-265a-11e9-964b-098563d0ecb0.png)

(I expected cupsd to show up listening on 631, and don't really understand why it doesn't, but that's a separate issue once I figure out what's up)

**Comment by dalance** [comment]
Thanks! I fixed it.
And I forgot to display port bound to IPv6 address. This may cause port 631 missing.
Could you try v0.3.1 or later?

**Comment by dcarosone** [comment]
Just tried current head and the columns are fixed!

The port thing turns out to be a permissions issue in /proc, as per the following from `netstat -ap`:

> (Not all processes could be identified, non-owned process info
>  will not be shown, you would have to be root to see it all.)

**Comment by dalance** [comment]
Right. Some columns ( like TCP/UDP/Read/Write ) can't be shown by permission issue.
If use `sudo procs`, all info should be shown.

**Comment by dcarosone** [comment]
Yep, PR incoming in a sec with a readme update.

I wonder if the display could distinguish:
 * listening ports:  `[123, 456]
 * not listening: `[]`
 * not able to tell because of permissions:  `  ` (empty, no braces)

**Comment by dcarosone** [comment]
Brilliant!
