### ISSUE TITLE
procs search case is not smart

### ISSUE THREAD

**Issue by Yof3ng** [dalance/procs#312]
If keyword contains uppercase character, case sensitive search. Otherwise case still keep sensitive search!!!
Although i set the case "Insensitive", it still keep sensitive search...
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/35987319/179341228-f077a667-4cfa-4460-8afd-74b7e033b534.png">

**Comment by dalance** [comment]
Smart case is released at v0.13.0 now.
