### ISSUE TITLE
Search case insensitive

### ISSUE THREAD

**Issue by sergiorgiraldo** [dalance/procs#321]
V 0.13

I have this on my config.toml:
```
[[columns]]
kind = "Command"
case = "Insensitive"

[search]
case = "Insensitive"
```

When looking for 'espanso', it should find both but only matches the lowercase. If looking for 'Espanso', only matches the uppercase. It should match both if case is insensitive.

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1144364/181907771-afe2930f-c45c-4fc3-be56-7867079ea962.png">
<img width="980" alt="image" src="https://user-images.githubusercontent.com/1144364/181907868-6ca32a32-d7cd-4c0c-8439-4e64024531f6.png">

**Comment by dalance** [comment]
The screenshot seems to show searching on pager (ex. `less`).
If you use `less`, the following config may be helpful.

```
export LESS='-I'
```

`Insensitive` of procs can be used like below:

```
$ procs espanso
// "espanso" "Espanso" "ESPANSO" will be shown
```
