### ISSUE TITLE
Underline is displayed when exiting watch mode on windows

### ISSUE THREAD

**Issue by shiena** [dalance/procs#34]
When you exit watch mode on windows, an underline is displayed at the top of the console.
procs is v0.9.1.

- cmd
![image](https://user-images.githubusercontent.com/1295639/73086643-5b302880-3f14-11ea-9480-0f238a05eb56.png)
- Windows Powershell
![image](https://user-images.githubusercontent.com/1295639/73086629-4f446680-3f14-11ea-8b99-d1c2bfb5e515.png)
- PowerShell Core 6
![image](https://user-images.githubusercontent.com/1295639/73086611-494e8580-3f14-11ea-82b1-ee8785d011d1.png)

**Comment by dalance** [comment]
Thank you for your report.
The issue can be reproduced on my environment.
I'll investigate it.

**Comment by dalance** [comment]
The issue is caused by a dependent library.
I sent the PR to fix it, but fixed release will take a little time.

**Comment by shiena** [comment]
console v0.9.2 has been released, which fixes `clean_screen` issues.
https://github.com/mitsuhiko/console/compare/0.9.0...0.9.2

**Comment by dalance** [comment]
I released v0.9.2.

**Comment by shiena** [comment]
Thank you!
