### ISSUE TITLE
Under Windows configuration file does not take effect

### ISSUE THREAD

**Issue by jc-fun** [dalance/procs#345]
After I will configuration files in the corresponding position, again and again trying to find the configuration file is not effective .  Under Linux doesn't this problem
![image](https://user-images.githubusercontent.com/58456995/186565984-3fa05294-33a2-48eb-af38-ad2daa08d7bf.png)

**Comment by dalance** [comment]
The path of README was wrong.
Could you try `~/AppData/Roaming/dalance/procs/config/config.toml`?

**Comment by jc-fun** [comment]
Thanks, this problem has been resolved

**Comment by jc-fun** [comment]
> The path of README was wrong. Could you try `~/AppData/Roaming/dalance/procs/config/config.toml`?

Thanks, this problem has been resolved
