### ISSUE TITLE
missing data: pgid, sess

### ISSUE THREAD

**Issue by bukzor-sentryio** [dalance/procs#359]
procs seems to have no ability to display the process-group or process-session IDs of processes. In linux I can get this from /proc or ps, but in macos ps has a bug displaying all session ids as 0 (while it displays pgid just fine). It would be excellent if procs would fill this gap.

(I hope this is helpful) This C program will display the pgid and sid of its own pid, in macos.

```!c
#include <stdio.h>
#include <unistd.h>

int main() {
  printf("pid: %d, process groupd id: %d, session ID: %d, ppid: %d\n",getpid(), getpgid(0), getsid(0), getppid());
}
```
  
  
```!sh
$ gcc getsid.c -o getsid ; ./getsid
pid: 25472, process groupd id: 25472, session ID: 25236, ppid: 25239
```

Some background information: https://superuser.com/q/1295565

**Comment by dalance** [comment]
Pgid and session id was added by https://github.com/dalance/procs/pull/150, but I forgot to update README.
You can add `Pgid` and `Session` like below.

```
$ ./getsid &
pid: 236553, process groupd id: 236553, session ID: 334041, ppid: 334041
$ procs --insert Session --insert Pgid getsid
 PID:▲  User  │ State Nice TTY    CPU MEM  VmSize    VmRSS TCP UDP  Read Write Session PGID   │ CPU Time Start            Elapsed  Docker │ Command
              │                   [%] [%] [bytes]  [bytes]         [B/s] [B/s]                │                                           │
 236553 hatta │ S        0 pts/62 0.0 0.0  4.129M 364.000K []  []      0     0 334041  236553 │ 00:00:00 2022/09/20 10:18 4seconds        │ ./getsid
```

In #150, session is not supported in macos.
I'll check the provided information and consider macos support.
But it may be difficult because I don't have a macos environment.

**Comment by dalance** [comment]
I added session ID support by `getsid`.
Could you try v0.13.1?

**Comment by bukzor-sentryio** [comment]
Confirmed working! Thanks.
