### ISSUE TITLE
Tree view: branch does not end properly when using filter

### ISSUE THREAD

**Issue by lightonflux** [dalance/procs#37]
When using a filter procs does not end a branch properly:

![Bildschirmfoto von 2020-01-28 18-36-12](https://user-images.githubusercontent.com/1377943/73289556-39c58a00-41fd-11ea-8858-8c4c0b8943a4.png)

On the left you see how htop display the last child in a sub tree when filtered (F4) and on the right procs.

htop:

```
├─ /usr/…
│  ├─
│  ├─
│  └─  ← this here
```

procs:

```
 │││└┬────
 │││ ├────
 │││ ├────
 │││ ├──── ← not very nice :(
```

(I am also not sure if the tree is at the correct column. htops visualization in front of the command make more sense IMHO)

**Comment by dalance** [comment]
Thank you for your report.
I improved tree view and released v0.9.4.
