### ISSUE TITLE
procs does't show tcp port in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [dalance/procs#375]
hello, I download binary release file , version is 0.13.1. copy file to /usr/local/bin to install, and no tcp port column when i start procs, `procs 8080` print nothing even i have a process listen to 8080 meanwhile.
`procs --insert TCP` will display tcp port. i want to show it default.

**Comment by dalance** [comment]
The default configuration is minimal because terminal may be small.
You can add tcp column by putting configration file.

https://github.com/dalance/procs#configuration
