### ISSUE TITLE
Compilation on darwin fails (0.13.2)

### ISSUE THREAD

**Issue by viraptor** [dalance/procs#379]
Building the recent version (0.13.1) fails with:
```
error[E0432]: unresolved import `crate::osx_libproc_bindings::proc_pid_rusage`
  --> /private/tmp/nix-build-procs-0.13.1.drv-0/procs-0.13.1-vendor.tar.gz/libproc/src/libproc/pid_rusage.rs:12:5
   |
12 | use crate::osx_libproc_bindings::proc_pid_rusage;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---------------
   |     |                            |
   |     |                            help: a similar name exists in the module: `PROC_PID_RUSAGE`
   |     no `proc_pid_rusage` in `osx_libproc_bindings`
```

**Comment by viraptor** [comment]
Confirmed failing on 0.13.2 as well.

**Comment by dalance** [comment]
Could you provide information about your environment?
The latest CI build for macOS seems to be success.

https://github.com/dalance/procs/actions/runs/3186932488/jobs/5198004915

**Comment by viraptor** [comment]
Sorry, I was too quick to report. This is an issue in libproc instead, I'll follow up there. (for the record, that's an issue in nixpkgs, 1.63, v11 sdk)
