### ISSUE TITLE
how do i know which config is used?

### ISSUE THREAD

**Issue by michabbb** [dalance/procs#420]
hi, i installed procs via snap (linux, kubuntu) and tried all paths i have seen in the readme but the output never changes.
so I guess procs is not using my config at all. it would be nice to see where procs is (really) looking for the config.
i tested `~/.procs.toml` also `~/.config/procs/config.toml` but none of these files are used.
btw... an `strace` didn't show me any info or file access ;(

thanks for any help.

**Comment by dalance** [comment]
procs searches `$XDG_CONFIG_HOME/procs/config.toml` not `~/.config/procs/config.toml `.
In snap environment, `$XDG_CONFIG_HOME` seems to be set to a different directory.
How about `~/snap/procs/config.toml` or `~/snap/procs/<revision>/config.toml` ?

**Comment by michabbb** [comment]
thanks a lot, it looks like the correct path for me is: `~/snap/procs/config.toml`. 👍
