### ISSUE TITLE
Respect `DOCKER_HOST` for reading docker info

### ISSUE THREAD

**Issue by WhyNotHugo** [dalance/procs#423]
`unix:///var/run/docker.sock` is the default path, but only used when running docker as root. When running docker as non-root the environment variable `DOCKER_HOST` defines the socket of the docker path.

**Comment by WhyNotHugo** [comment]
Maybe changing  [`ConfigDocker::default()`](https://github.com/dalance/procs/blob/8005f1aefb78f99dfc165fbb833c1e5c45574859/src/config.rs#L619-L625) would make sense here?

**Comment by WhyNotHugo** [comment]
I can submit a patch if that seems like a reasonable approach.

**Comment by dalance** [comment]
I think it seems to be good.
