### ISSUE TITLE
Smart case search seems broken in 0.13.4

### ISSUE THREAD

**Issue by philipm-domuso** [dalance/procs#428]
Searching for `/xcode` should trigger case-insensitive search:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/123421288/216499925-d0d7edcb-cf03-44fe-9c4c-5ef02fcbf40d.png">

But doesn't find anything.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/123421288/216499871-2f54ae19-a11a-468e-817e-0ce42764ba02.png">

Searching for `/Xcode` works, though:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/123421288/216500144-ccdfb3b8-3380-4f77-89d0-74a38b09c89b.png">

* macOS Ventura 13.1 on Mac M1
* procs v0.13.4

**Comment by dalance** [comment]
The screenshot seems to show searching on pager (ex. `less`).
If you use `less`, the following config may be helpful.

```
export LESS='-i'
```

Smartcase of procs can be used like below:

```
$ procs xcode
// will be show "xcode" "XCODE" "Xcode"
$ procs Xcode
// will be show "Xcode" only
```
