### ISSUE TITLE
Trimming command column on the left

### ISSUE THREAD

**Issue by mredaelli** [dalance/procs#429]
I'm a NixOS user, so most of the time the output of `procs` looks like this:

![image](https://user-images.githubusercontent.com/3073833/216721540-ef82fb4e-78f0-4273-97d2-bef10c9d1d8d.png)

and it's hard to tell what the program is.

With `ps` there's the `c` option. Is there something similar in `procs`?

**Comment by dalance** [comment]
I added `FileName` column as the same as `comm` of ps.

**Comment by mredaelli** [comment]
Awesome, thank you!
