### ISSUE TITLE
rustc version

### ISSUE THREAD

**Issue by DavideSampietro** [dalance/procs#44]
I'm trying to install via `cargo install`, but get compile error.
Which version of `rustc` shall I use?

**Comment by dalance** [comment]
I checked the latest stable.

```
$ rustc --version
rustc 1.41.1 (f3e1a954d 2020-02-24)
```

Could you show the compile error and your environment ( Linux, macOS, or Windows)?

**Comment by DavideSampietro** [comment]
No compile errors on `1.41.1`. I don't know rust, but I guess it was a syntax error.
I was using an outdated toolchain because another project didn't compile on latest instead.

Thanks!
