### ISSUE TITLE
Column UserLogin shows 4294967295

### ISSUE THREAD

**Issue by steffenbusch** [dalance/procs#441]
I'm a big fan of the **UserLogin** column in `procs`  since I'm often logged in as "my" user, but `su` to another user to start certain jobs.
For me, it's a bit confusing, when the `procs` output shows the value of `4294967295` (Hex FFFF FFFF) in that column.

![image](https://user-images.githubusercontent.com/37350514/222953453-561781e3-5ede-42c6-80cd-2b1acfdf559a.png)

Wouldn't it make sense to hide that special value and display just an empty string?

**Comment by dalance** [comment]
Thanks.
I understood that `0xffffffff` means login uid is not set.
At the next version, it will be fixed.

**Comment by dalance** [comment]
I released v0.14.0.
