### ISSUE TITLE
[Windows, internal pager] Arrow keys doesn't work before other key is pressed

### ISSUE THREAD

**Issue by CarterLi** [dalance/procs#443]
Steps:

1. Start procs with pager enabled
2. Press arrow key ( up or down doesn't matter ): nothing happens
3. Scroll mouse wheel: nothing happens
4. Press enter once: nothing happens
5. Press arrow key: work as expected ( scroll up or down )
6. Press enter: work as expected ( scroll down )
7. Scroll mouse whell: work as expected

* Windows 11 x64 (22H2)
* Windows Terminal Preview (1.17.10235.0)
* procs "0.14.0 ( rev: 915d891, rustc: 1.67.1, build at: 2023/03/07 09:06:37 )" (Installed by scoop)

**Comment by dalance** [comment]
Thanks.
The issue seems to occur on all platforms.
I'll investigate it.

https://github.com/async-rs/async-std/issues/1055
https://github.com/tokio-rs/tokio/issues/5535

**Comment by dalance** [comment]
This issue was fixed by https://github.com/dalance/termbg/pull/29.
