### ISSUE TITLE
homebrew v0.9.16 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [dalance/procs#45]
relates to https://github.com/Homebrew/homebrew-core/pull/51035

```
==> cargo install --locked --root /usr/local/Cellar/procs/0.9.16 --path .
Last 15 lines from /Users/ruichen/Library/Logs/Homebrew/procs/01.cargo:
   Compiling regex v1.3.4
   Compiling idna v0.1.5
error: failed to run custom build command for `proc-macro-error-attr v0.4.10`
```

**Comment by dalance** [comment]
Thank you for your report.
It seems to be caused by https://gitlab.com/CreepySkeleton/proc-macro-error/issues/8.
I'll update the crate to fix.

**Comment by dalance** [comment]
I released v0.9.17.
Could you try it?

**Comment by chenrui333** [comment]
Sure, doing it now.

**Comment by chenrui333** [comment]
Confirmed it is fixed now. Thanks for the quick turnaround.
