### ISSUE TITLE
Failed to build procs because of minus dependency using E0658 ­— use of unstable library feature 'int_log'

### ISSUE THREAD

**Issue by kierun** [dalance/procs#486]
## Steps to reproduce

1. Be on Ubuntu 22.04.2 LTS x86_64
2. Run `cargo install procs`. 

## What was expected

The version of `procs` is updated from `v0.13.4` (the current installed via cargo), to `v0.14.0`.

## What happened

The code does not install due to minus dependency using E0658 ­— use of unstable library feature 'int_log'.

Here is the relevant part of the cargo run:

```bash
√ ; procs --version
procs 0.13.4
√ ; whence procs
/home/usr/.cargo/bin/procs
√ ; cargo --version
cargo 1.65.0
√ ; cargo install procs
[…]
   Compiling minus v5.3.1
error[E0658]: use of unstable library feature 'int_log'
   --> /home/yann/.cargo/registry/src/github.com-1ecc6299db9ec823/minus-5.3.1/src/state.rs:460:28
    |
460 |             old_line_count.ilog10() + 1
    |                            ^^^^^^
    |
    = note: see issue #70887 <https://github.com/rust-lang/rust/issues/70887> for more information

error[E0658]: use of unstable library feature 'int_log'
   --> /home/yann/.cargo/registry/src/github.com-1ecc6299db9ec823/minus-5.3.1/src/state.rs:469:28
    |
469 |             new_line_count.ilog10() + 1
    |                            ^^^^^^
    |
    = note: see issue #70887 <https://github.com/rust-lang/rust/issues/70887> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `minus` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

## Additional notes

I tried to install it on Fedora 38 via cargo, and guess what? It worked… 

```bash
√ ; cargo --version
cargo 1.70.0
√ ; whence procs
/home/usr/.cargo/bin/procs
√ ; procs --version
procs 0.14.0
√ ; bat /etc/fedora-release
───────┬────────────────────────────────────────────────────────────────────────
       │ File: /etc/fedora-release
───────┼────────────────────────────────────────────────────────────────────────
   1   │ Fedora release 38 (Thirty Eight)
───────┴────────────────────────────────────────────────────────────────────────
```

**Comment by dalance** [comment]
`ilog10` was stabilized at Rust 1.67.0.
So Rust 1.65.0 can't be supported now.

**Comment by kierun** [comment]
> `ilog10` was stabilized at Rust 1.67.0. So Rust 1.65.0 can't be supported now.

Because, of course, Ubuntu is behind the times once more… :facepalm: :rage:

Any suggestions as to how to update the Ubuntu version without breaking everything? Is there something similar to [pix](https://pypa.github.io/pipx/) for rust?

**Comment by dalance** [comment]
How about the official installation way?

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

This install the latest Rust compiler under `~/.cargo/bin`.
So It doesn't break your system enviroment.

**Comment by kierun** [comment]
> How about the official installation way?
> 
> ```
> $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> ```
> 
> This install the latest Rust compiler under `~/.cargo/bin`. So It doesn't break your system enviroment.

Perfect! 

Thank you very much for all your help. It is much appreciated.
