### ISSUE TITLE
Default pager cuts off rightmost columns in small terminal

### ISSUE THREAD

**Issue by medusacle** [dalance/procs#5]
When running `procs` without any arguments, the default pager of `less` is now launched. This is great ! However, when the number of column of the terminal is less than required to display the full width of the table, everything to the right of that will be cut off, This tends to lose the most important column, `Command`.

it's possible to work around this using:
```bash
procs --color always | less -SR
```
…which launches a pager that is able to scroll left/right to see all the information. But I think it would be useful to have this as default.

**Comment by frostRed** [comment]
same to me

**Comment by dalance** [comment]
Thanks! I'll change default pager option and cut off behavior.

**Comment by dalance** [comment]
I released v0.4.4.

**Comment by medusacle** [comment]
Just re-tested and can confirm that this is solved with latest version, thank you !
