### ISSUE TITLE
ps minimalistic by default

### ISSUE THREAD

**Issue by matu3ba** [dalance/procs#55]
For users coming from `ps` getting the most used options to simply run (ie only showing PID TTY TIME CMD) would be useful.  
The output is a bit overwhelming in size and it is not clear to me from the start how to reduce the columns or select only some of them.

**Comment by dufferzafar** [comment]
Yeap!

By default, `procs` shows all the columns. To me the most important one is `command` and it is shown at the end (which is understandable) but it doesn't wrap the lines, so they get chopped off!

I currently have to use it with `-p always`, which is not the best experience.

**Comment by dalance** [comment]
The columns can be customized by a configuration file.
Is this insufficient?

https://github.com/dalance/procs#configuration

**Comment by dufferzafar** [comment]
Thanks @dalance . I should've read the Readme properly then. I didn't even bother scrolling. Just downloaded the binary and tried it out. Will try making a config that works for me.

**Comment by dalance** [comment]
Exactly the README is too long.
I added the links to each sections.

**Comment by matu3ba** [comment]
> The columns can be customized by a configuration file.
> Is this insufficient?
> 
> https://github.com/dalance/procs#configuration

I do like the flexibility of the config file. However hardcoding the config for the columns is abit restricting (in contrast to `ps`), but probably fine for pre `1.x`.

I do assume `keyword` does match any output of `procs`. This is missing in the `--help` and not explained in the README.

**Comment by dalance** [comment]
OK. I agree the current default config is too large.
I'll change the default config to fit 80x24 terminal like below:

![image](https://user-images.githubusercontent.com/4331004/79428615-62417100-8001-11ea-9647-4c48951df362.png)

Additionally, I'll add a message if configuration file is not found.

![image](https://user-images.githubusercontent.com/4331004/79428893-c6643500-8001-11ea-8c40-2981f3d5a2d3.png)

**Comment by dalance** [comment]
I released v0.10.0.
