### ISSUE TITLE
tree + filter: an option to show full branches

### ISSUE THREAD

**Issue by indeyets** [dalance/procs#59]
currently, whenever I run `procs --tree postgres` I can see only the items which actually have "postgres" in their title. This is fine for normal mode, but…

It would be really useful if in tree mode the output would also include parent and child processes. Probably they could be shown in faded colors.

The main point of tree-mode is to show the context and I expect to be able to see this context even if filtering is involved.

To put it in other terms: in tree-mode, filter should be applied to branches, not leaves

**Comment by dalance** [comment]
Thank you for your suggestion.
I released v0.10.3 which enables branch filtering.

**Comment by indeyets** [comment]
thank you! works perfectly
