### ISSUE TITLE
Store Mac config in same location as Linux

### ISSUE THREAD

**Issue by texastoland** [dalance/procs#63]
Related discussion and libraries that handle it in nushell/nushell#893.

**Comment by bhagatparwinder** [comment]
I fully support this mission 🚀 

If not the same folder, is there a possibility to set it to a custom folder (so I can sync it to other devices by placing it in Dropbox)?

**Comment by krnik** [comment]
To me it sounds like a good idea, in my case what matters is the ability to influence where the program I'm using stores its stuff. IMO the simpler configuration the better.

Configuration files could be checked in the following locations:
```
1) XDG_CONFIG_HOME/procs/config.toml
2) HOME/procs/config.toml
3) HOME/.procs.toml
```

I have implemented it for myself (because of the support for XDG env variable) so I can add and easily access the config easily both on mac and linux https://github.com/krnik/procs/commit/db6a6ab9684469bb4c12a8ebfbf197cb7a5a2075

**Comment by lilyball** [comment]
I really hate that `directories` uses `~/Library/Application Support` on macOS. That's appropriate for GUI apps, but CLI apps really should be using the XDG stuff. This is something I complained about on that crate years ago 😣

In any case, this really should be using `${XDG_CONFIG_HOME:~/.config}/procs/config.toml` just like Linux.

@ghost `HOME/procs/config.toml` is not an appropriate path. No CLI tool should be using non-dotted config dirs in the home folder.

As for alternative locations, such as Dropbox (/cc @bhagatparwinder), there are two reasonable approaches:

1. Add an env var that points to an alternative config. This is a good idea in general so alternative configs can be provided via a shell alias (that offers the different location) or via any program that might want to wrap `procs` (or via package managers like Nix that might want to offer configuration of `procs` in the Nix config).
2. Ensure that symlinks are supported.

Really both should be done. For Dropbox, I'd suggest just symlinking into Dropbox so the config is used even with a damaged/absent environment. But the env var should be available too for the reasons specified.

**Comment by dalance** [comment]
In my understanding, this issue was resolved by https://github.com/dalance/procs/issues/58.
I'll close it, but if there is any remaining issue, please open another issue.
