### ISSUE TITLE
CPU usage more than 100%

### ISSUE THREAD

**Issue by lum-node** [dalance/procs#65]
Run mocha tests. The 'procs -w' (interval 1 sec.) shows 'node' process CPU load more than 100%, while standard 'top' is none.

**Comment by dalance** [comment]
The value of CPU usage has more error than `top` because the sampling interval (not watch interval) of `procs` is shorter than `top`.
I think `--interval` option can reduce the error like below:

```
$ procs -w --interval 1000
```

The default value of `interval` is 100ms. This is because of quick response.
