### ISSUE TITLE
WinGet-based installation

### ISSUE THREAD

**Issue by zkat** [dalance/procs#66]
It would be really great to be able to install procs on Windows through the [windows package manager, `winget`](https://docs.microsoft.com/en-us/windows/package-manager/winget/).

**Comment by dalance** [comment]
Now winget doesn't support zip-based installation.

```
# InstallerType is a required field.  Supported types are inno, wix, msi, nullsoft, zip, appx, msix and exe.
# The winget command tool uses this value to assist in installing this application.
# If the value is an exe, you will need to provide the quiet switches.
# zip is not supported in this preview (5/24/2020)  
# Restrictions: [min: 1, max:40] 
InstallerType: msix
```

I'll try winget after it is supported because I can't provide another Windows installer like `.msi`.

**Comment by dalance** [comment]
I'm trying to add procs to winget.
https://github.com/microsoft/winget-pkgs/pull/122834

**Comment by dalance** [comment]
Now winget can be used.

```
$ winget install procs
```
