### ISSUE TITLE
Columns Missing Info, Error Instead

### ISSUE THREAD

**Issue by asheroto** [dalance/procs#69]
Strange problem...

![image](https://user-images.githubusercontent.com/49938263/89637529-eac57500-d86f-11ea-9bd5-65efd2d22f0f.png)

Using Debian 10.  Used the procs binary from the releases zip for Linux.

**Comment by dalance** [comment]
Could you check the following instruction?

https://github.com/dalance/procs#less-setting

**Comment by asheroto** [comment]
Ah, that was the issue.   Thank you.
