### ISSUE TITLE
Adding a new installation method to the README

### ISSUE THREAD

**Issue by curry798** [dalance/procs#710]
Hi, we have implemented a lightweight [package manager using shell and awk](https://www.x-cmd.com/pkg/).
It helps you download procs release packages from the internet and extract them into a unified directory for management, without requiring root permissions.

I mean, can the installation method provided by x-cmd be added to the procs README?
[The installation method for the x command](https://www.x-cmd.com/start/)

install procs:
```bash
x env use procs
or 
x procs # Download procs, and invoke procs in a way that does not affect the current environment
```
[procs demo](https://www.x-cmd.com/pkg/procs): x-cmd recorded a demo and article for procs

I apologize in advance if it's not appropriate to raise this topic using a GitHub issue.
Looking forward to your reply :) !

**Comment by dalance** [comment]
Thanks!
If you create a PR to add it, I merge it.

**Comment by curry798** [comment]
> Thanks! If you create a PR to add it, I merge it.

HI, thank you for your reply. I've submitted the [PR](https://github.com/dalance/procs/pull/711).
