### ISSUE TITLE
snaps install on ubuntu 20.02 : ld.so object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by arthurlogilab** [dalance/procs#73]
```
procs
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
```

**Comment by dalance** [comment]
I tried to reproduce it on Ubuntu 20.04 clean image, but it couldn't be reproduced.
The following site may be helpful.

https://stackoverflow.com/questions/53825857/error-ld-so-object-libgtk3-nocsd-so-0-from-ld-preload-cannot-be-preloaded
