### ISSUE TITLE
Display problem when using via snap on Ubuntu 20.02

### ISSUE THREAD

**Issue by arthurlogilab** [dalance/procs#74]
![Screenshot from 2020-09-23 12-15-09](https://user-images.githubusercontent.com/445200/93999742-7babcd80-fd96-11ea-9afa-933ad5967dd5.png)

**Comment by dalance** [comment]
Could you try the following config?

https://github.com/dalance/procs#less-setting

**Comment by arthurlogilab** [comment]
This setting fixes it. Shame it doesn't work out of the box, this might deter some new users. Thanks for the prompt response and the fix!

**Comment by dalance** [comment]
Thanks. I will try to fix it by calling less with `LESSCHARSET` internally.
