### ISSUE TITLE
on terminal width overflow, use pager

### ISSUE THREAD

**Issue by sinapis** [dalance/procs#76]
i think cutting input is not an optimal default. the user does not know or expect input to be cut. 
when procs uses more then terminal height, pager is used by default. why not when more than terminal width?
even if you disagree about default, i think it's better to at least have the option to use pager when there is width overflow.

**Comment by dalance** [comment]
Thank you for your request.
I added `detect_width` option to detect width overflow, and released v0.10.7.
You can enable this feature in `config.toml` like below:

```toml
[pager]
mode = "Auto"
detect_width = true
```

**Comment by sinapis** [comment]
Excellent!! Much appreciated!
