### ISSUE TITLE
[FR] Add option to specify output ala -o %cpu

### ISSUE THREAD

**Issue by NightMachinary** [dalance/procs#77]
I currently use:
```
function  pt-cpu() {
    procs --or "$@" | gtail -n +3 | awk '{print $4}'
}
```
But this seems brittle and inelegant.

**Comment by dalance** [comment]
Thank you for you feature request.
I added `--only` and `--no-header` option, and released v0.10.6.
For example, you can do like below:

```
$ procs --no-header --only usagecpu
```
