### ISSUE TITLE
Completion(s)

### ISSUE THREAD

**Issue by xeho91** [dalance/procs#86]
First of all, thank you for this amazing program! It makes viewing processes experience much smoother and readable.

**Is there any chance to develop completion(s) system for these shells below?**
- Bash
- Zsh
- Fish

I can't remember by memory which options (flags) are available, so using a Tab to view the available options after typing `procs -<TAB>` will be a time saver.

**Comment by dalance** [comment]
I added `--completion` option, and released v0.10.9.
https://github.com/dalance/procs#shell-completion

**Comment by xeho91** [comment]
Wow, that was fast. They work perfectly, thank you very much!
